#ifndef STEGO_BACKEND_LOGGER_HPP
#define STEGO_BACKEND_LOGGER_HPP

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logDebug)
Q_DECLARE_LOGGING_CATEGORY(logInfo)
Q_DECLARE_LOGGING_CATEGORY(logWarning)
Q_DECLARE_LOGGING_CATEGORY(logCritical)

Q_DECLARE_LOGGING_CATEGORY(producer)
Q_DECLARE_LOGGING_CATEGORY(consumer)

#endif //STEGO_BACKEND_LOGGER_HPP
